services:
  wordpress1:
    image: wordpress
    restart: unless-stopped
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: 10.0.3.185
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: Paula123@
    ports:
      - "8080:80"
    volumes:
      - /var/www/html/wp-content/:/var/www/html/wp-content/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 2

  wordpress2:
    image: wordpress
    restart: unless-stopped
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: 10.0.3.185
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: Paula123@
    ports:
      - "8081:80"
    volumes:
      - /var/www/html/wp-content/:/var/www/html/wp-content/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 2
    depends_on:
      wordpress1:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx-wordpress   
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx-configuration/:/etc/nginx/conf.d/
    depends_on:
      wordpress1:
        condition: service_healthy
      wordpress2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 10s
      retries: 2
